### ISSUE TITLE
Method to search author by name

### ISSUE THREAD

**Issue by kwcooper** [danielnsilva/semanticscholar#2]
Hello! Great software. However, it proves difficult to find a list of the author code strings ie. 
`author = sch.author(2262347)`
Is there a method to search by name? Else, what would be a good way to compile a list of the codes?

**Comment by danielnsilva** [comment]
Hello @kwcooper . First of all, you're right. Unfortunately, however, Semantic Scholar's RESTful API service does not provide any resources to search author by name.
That said, I don't know whether there is a good way to compile a list of author ID. Semantic Scholar [open corpus](http://s2-public-api-prod.us-west-2.elasticbeanstalk.com/corpus/download/) available to download would be a option, but it's a lot of data to deal with. Another possibility is to crawl Semantic Scholar's [search page](https://www.semanticscholar.org/search), which is not the initial purpose of this project.
This is all theoretical though because I haven't tried any of this.

**Comment by kwcooper** [comment]
Thanks Daniel for your input! I'll have to think of a good way to go about it.
