### ISSUE TITLE
Including year in paper search increases number of results

### ISSUE THREAD

**Issue by jacbel** [danielnsilva/semanticscholar#45]
I noticed some unexpected behavior when including year as a query parameter in the search for papers. Specifically, including the year drastically increases the number of results returned. This does not seem right as it should rather filter out a large number of publications.

Example:
```{python}
from semanticscholar import SemanticScholar
sch = SemanticScholar()

results = sch.search_paper('Computing Machinery and Intelligence')
print(f'{results.total} results without year parameter.')

results = sch.search_paper('Computing Machinery and Intelligence', year=1950)
print(f'{results.total} results with year parameter.')
```

The first search returns 510 results, the second more than 250k results.

Any idea why this might be the case?

**Comment by danielnsilva** [comment]
I agree this does not seem right, but actually, the query results in only 10 items. I think the problem is with the ```total``` field value in the S2AG API response which may be unclear.

```python
from semanticscholar import SemanticScholar
sch = SemanticScholar()
results = sch.search_paper('Computing Machinery and Intelligence', year=1950)
print(f'{len(results.items)} results with year parameter.')
```

Output:
```console
10 results with year parameter.
```

From the [official doc](https://api.semanticscholar.org/api-docs/graph#tag/Paper-Data/operation/get_graph_get_paper_search): "Because of the subtleties of finding partial phrase matches in different parts of the document, be cautious about interpreting the total field as a count of documents containing any particular word in the query."

**Comment by jacbel** [comment]
Thanks for the fast reply and for clarifying this!
In any case, my confusion seems to stem from the API response itself rather than your awesome package. Will close the issue.
