### ISSUE TITLE
Support for asynchronous programming

### ISSUE THREAD

**Issue by firmianay** [danielnsilva/semanticscholar#52]
Hello! I'm building a database that requires a lot of requests. The requests library makes this process very slow. Can you support aiohttp to achieve asynchrony and improve request efficiency?

**Comment by danielnsilva** [comment]
I understand that your concern is about library performance in general, rather than specifically adopting `aiohttp`.

Some initial considerations came to mind while reading your suggestion. For instance, would it be useful to provide both sync and async options?

Besides, while `aiohttp` is a popular choice for asynchronous HTTP requests in Python, it's essential to consider alternatives and evaluate which approach would be best suited for this project.

Another alternative to consider is the `httpx` library, which provides built-in support for both synch and async requests. It aims to be a drop-in replacement for `requests` while offering additional features and performance improvements.

Additionally, before changing the HTTP library, it may be worth exploring other approaches, such as creating sessions using connection pooling.

Please note that the thoughts I've shared here are preliminary, and I will need some time to fully assess the situation and come up with a final answer. Meanwhile, any futher help/suggestion will be appreciated.

**Comment by gabriel-trigo** [comment]
Added a pull request implementing this functionality! @danielnsilva @firmianay
