### ISSUE TITLE
Source of the references and inconsistency

### ISSUE THREAD

**Issue by realliyifei** [danielnsilva/semanticscholar#78]
What is the source of these references by `sch.get_paper_references`? 

I notice that a few of them are not consistent with the ground truth references in the pdf (i.e. missing references, having extra references, or the references are not the same ones). 

Also, the ordering is not the same as ground truth so cannot map to the in-context citation index.

**Comment by danielnsilva** [comment]
[This paper ](https://www.semanticscholar.org/paper/The-Semantic-Scholar-Open-Data-Platform-Kinney-Anastasiades/cb92a7f9d9dbcf9145e32fdfa0e70e2a6b828eb1) states that they use multiple data sources and extract information from the PDFs. However, I'm unaware of the internal specifics, so I can't determine the cause of the inconsistency reported. Since the semanticscholar package wraps the S2 API, for this issue, consider posting in their [official GitHub repository](https://github.com/allenai/s2-folks).

**Comment by danielnsilva** [comment]
Closing this issue for now. Please reopen if you have further questions.
